-- Up Migration
CREATE TABLE IF NOT EXISTS Users(
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    salt VARCHAR NOT NULL,
    id UUID NOT NULL PRIMARY KEY
)
-- Down Migration
DROP TABLE IF EXISTS Users